### ISSUE TITLE
Great work but there is already another package 

### ISSUE THREAD

**Issue by Casperhr** [MihaelIsaev/FCM#1]
Hi @MihaelIsaev Great work with the package

Nodes needs a FB push package soon also.
We previously used https://github.com/mdab121/vapor-fcm by @mdab121
That package is not ready for vapor 3 yet.

And we a had a conversation with him to move it to the community to get more features in. 
Is that something you could be interested in also?

**Comment by MihaelIsaev** [comment]
Hey @Casperhr thank you.

Yeah I saw mdab121's lib before I started developing my own.
I waited three month and as there are no movings to port mdab121's lib to Vapor 3 I made a decision to create fcm lib by myself because I need push notifications functionality on my projects right now.

You could use this package in your projects and I'm interested and appreciate pull requests with new features. Hope that my package will be useful for you.

**Comment by mdab121** [comment]
Hey @MihaelIsaev. My package will be ready for vapor 3 soon. Sorry for the delay ;)
