### ISSUE TITLE
Warning when configuration FCM: `Cannot modify client configuration after client has been used`

### ISSUE THREAD

**Issue by sroebert** [MihaelIsaev/FCM#35]
When setting the configuration of FCM, I get the warning from Vapor: `Cannot modify client configuration after client has been used.`.

This happens because FCM is trying to set `application.http.client.configuration.ignoreUncleanSSLShutdown` to `true` after using the `application.client` property in the following code:

```swift
public init(application: Application) {
    self.init(application: application, client: application.client)
}
```

I'm wondering, does this configuration really need to be set to `true` in the first place (as there is no documentation on why this is done)? If it is needed, this code probably needs to be moved to the public init with the application, to avoid the warning and actually setting the value to `true`.

**Comment by MihaelIsaev** [comment]
That's the good question sir. As far as I remember Google servers always do `uncleanSSLShutdown` and we had problems with requests to Firebase, that's why this setting appeared in the lib.

You could scroll [that old chat a bit](https://discord.com/channels/431917998102675485/519613337638797315/667456382186029057) just to read that nobody knows why Google won't do clean shutdown..

> If it is needed, this code probably needs to be moved to the public init with the application

I tried to move `app.fcm.configuration = ...` to the top of my `configure.swift` and I still see the warning.
Then I set a breakpoint in [Vapor sources at line 45](https://github.com/vapor/vapor/blob/66cbe3c34140b3638f89c6441eec0db962ece9b1/Sources/Vapor/HTTP/Client/Application%2BHTTP%2BClient.swift#L45) and debugger never stopped on it, so it seems that HTTP configuration is set somewhere in the very beginning under the hood and it is impossible to change it from the outside later.

Maybe Google started doing clean ssl shutdown? I tried this request today

```swift
app.client.get("https://www.google.com").whenComplete {
    switch $0 {
    case .failure(let error): print("google.com error: \(error)")
    case .success: print("google.com success")
    }
}
```
and it prints `google.com success` so it seems clean ssl shutdown is here 🎉

And it seems that the lib works well for the very long time already and I have no claims from the users and myself as well.

So it means that we could just delete code at lines 38-40 in [FCM.swift](https://github.com/MihaelIsaev/FCM/blob/54a380a67a5ecbaf780c1f071048fe867c9ce18a/Sources/FCM/FCM.swift#L38) since it doesn't do any job anyway.

@sroebert would you like to send pull request?

**Comment by sroebert** [comment]
I fixed it in my code for now, by already setting the value before configuring `FCM`:

```swift
app.http.client.configuration.ignoreUncleanSSLShutdown = true
app.fcm.configuration = ...
```

But I can definitely make a PR for removing this yes: #36
